### ISSUE TITLE
loss become NAN with Taichi 0.4.0

### ISSUE THREAD

**Issue by SJHNJU** [yuanming-hu/difftaichi#10]
I install taichi-nightly on OS X  and try to run the demo: diffmpm.py, diffmpm3d.py, liquid.py.

However the **loss become NAN** on the second iteration.

WHY???

**Comment by yuanming-hu** [comment]
Hi, thanks for reporting. Which taichi version, device (CPU/GPU), and OS are you using?

**Comment by SJHNJU** [comment]
Thanks! The configurations are as follows:
taichi-nightly (0.4.0)
CPU
MacOS Mojave(10.14.3)

**Comment by yuanming-hu** [comment]
Thank you. I can reproduce this on my end now. I'll fix it later. Please try Taichi v0.3.25 and see if it works for you.

**Comment by yuanming-hu** [comment]
Fixing related issues. Taichi v0.3.18 is the version that works.

**Comment by yuanming-hu** [comment]
Update: this should be fixed in Taichi v0.4.1. Please update and let me know if your issue is resolved.  Thanks so much for reporting!

**Comment by SJHNJU** [comment]
The issue is resolved, Great job!!!
Lots of respect, Thank you!
