### ISSUE TITLE
PyTorch interface? (not an issue)

### ISSUE THREAD

**Issue by JaroslavVitku** [yuanming-hu/difftaichi#12]
Hi, I've found your simulator and it looks really nice. 

I wanted to ask whether there is possibility to interface the environment (including gradients) with PyTorch. And if not, how complicated this might be to do on my own?

Best,
Jarda

**Comment by yuanming-hu** [comment]
Hi Jarda, please find sample PyTorch interfaces here: https://github.com/taichi-dev/taichi/blob/master/tests/python/test_torch_ad.py

**Comment by JaroslavVitku** [comment]
Great, thank you!
