### ISSUE TITLE
No examples working (ubuntu 19.01 and 18.01)

### ISSUE THREAD

**Issue by tbarton16** [yuanming-hu/difftaichi#21]
I can load the tai chi library, but all examples crash with `[Taichi] version 0.5.3, cuda 10.1, commit 6fa3be84, python 3.6.7
n_objects= 6    n_springs= 11
[W 02/29/20 10:15:14.815] [taichi_llvm_context.cpp:module_from_bitcode_file@186] Bitcode loading error message:
Invalid bitcode signature
[E 02/29/20 10:15:14.815] [taichi_llvm_context.cpp:module_from_bitcode_file@188] Bitcode /home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/../lib/runtime_x64.bc load failure.
[E 02/29/20 10:15:14.815] Received signal 6 (Aborted)
`
**On my 18.01 ubuntu install, it crashes with** :`[Taichi version 0.5.2, cuda 10.1, commit 4d56959a]
[E 02/28/20 17:16:09.152] Received signal 11 (Segmentation fault)

Taichi Compiler Stack Traceback 
/home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::signal_handler(int)
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fdb8e6abf20]
/home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::create_window()
/home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::GUI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, bool)
/home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0xcc6d8c) [0x7fdb6e8ded8c]
/home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0xcc6c8f) [0x7fdb6e8dec8f]
/home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0xb25504) [0x7fdb6e73d504]
python3(_PyMethodDef_RawFastCallDict+0x24d) [0x55877c836afd]
python3(_PyCFunction_FastCallDict+0x21) [0x55877c836c81]
python3(_PyObject_Call_Prepend+0x63) [0x55877c835313]
python3(PyObject_Call+0x6e) [0x55877c82706e]
python3(+0xacc70) [0x55877c7acc70]
python3(_PyObject_FastCallKeywords+0x128) [0x55877c8804e8]
python3(_PyEval_EvalFrameDefault+0x5379) [0x55877c8d50b9]
python3(_PyEval_EvalCodeWithName+0x2f9) [0x55877c814729]
python3(_PyFunction_FastCallDict+0x400) [0x55877c815a90]
python3(_PyObject_Call_Prepend+0x63) [0x55877c835313]
python3(+0x17f72a) [0x55877c87f72a]
python3(_PyObject_FastCallKeywords+0x128) [0x55877c8804e8]
python3(_PyEval_EvalFrameDefault+0x5787) [0x55877c8d54c7]
python3(_PyEval_EvalCodeWithName+0x2f9) [0x55877c814729]
python3(PyEval_EvalCodeEx+0x44) [0x55877c815654]
python3(PyEval_EvalCode+0x1c) [0x55877c81567c]
python3(+0x22bcb4) [0x55877c92bcb4]
python3(PyRun_FileExFlags+0xa1) [0x55877c936191]
python3(PyRun_SimpleFileExFlags+0x1c3) [0x55877c936383]
python3(+0x237475) [0x55877c937475]
python3(_Py_UnixMain+0x3c) [0x55877c93759c]
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
python3(+0x1dfb50) [0x55877c8dfb50]
`
Have you guys seen either of these issues?

**Comment by tianjuxue** [comment]
> I can load the tai chi library, but all examples crash with `[Taichi] version 0.5.3, cuda 10.1, commit 6fa3be84, python 3.6.7 n_objects= 6 n_springs= 11 [W 02/29/20 10:15:14.815] [taichi_llvm_context.cpp:module_from_bitcode_file@186] Bitcode loading error message: Invalid bitcode signature [E 02/29/20 10:15:14.815] [taichi_llvm_context.cpp:module_from_bitcode_file@188] Bitcode /home/theresa/.conda/envs/conda_env/lib/python3.6/site-packages/taichi/core/../lib/runtime_x64.bc load failure. [E 02/29/20 10:15:14.815] Received signal 6 (Aborted) `
> On my 18.01 ubuntu install, it crashes with :`[Taichi version 0.5.2, cuda 10.1, commit 4d56959a]
> [E 02/28/20 17:16:09.152] Received signal 11 (Segmentation fault)
> 
>     * Taichi Compiler Stack Traceback *
> 
> 
> /home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::signal_handler(int)
> /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fdb8e6abf20]
> /home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::create_window()
> /home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::GUI(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, int, int, bool)
> /home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0xcc6d8c) [0x7fdb6e8ded8c]
> /home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0xcc6c8f) [0x7fdb6e8dec8f]
> /home/tbarton1/anaconda3/envs/py37/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0xb25504) [0x7fdb6e73d504]
> python3(_PyMethodDef_RawFastCallDict+0x24d) [0x55877c836afd]
> python3(_PyCFunction_FastCallDict+0x21) [0x55877c836c81]
> python3(_PyObject_Call_Prepend+0x63) [0x55877c835313]
> python3(PyObject_Call+0x6e) [0x55877c82706e]
> python3(+0xacc70) [0x55877c7acc70]
> python3(_PyObject_FastCallKeywords+0x128) [0x55877c8804e8]
> python3(_PyEval_EvalFrameDefault+0x5379) [0x55877c8d50b9]
> python3(_PyEval_EvalCodeWithName+0x2f9) [0x55877c814729]
> python3(_PyFunction_FastCallDict+0x400) [0x55877c815a90]
> python3(_PyObject_Call_Prepend+0x63) [0x55877c835313]
> python3(+0x17f72a) [0x55877c87f72a]
> python3(_PyObject_FastCallKeywords+0x128) [0x55877c8804e8]
> python3(_PyEval_EvalFrameDefault+0x5787) [0x55877c8d54c7]
> python3(_PyEval_EvalCodeWithName+0x2f9) [0x55877c814729]
> python3(PyEval_EvalCodeEx+0x44) [0x55877c815654]
> python3(PyEval_EvalCode+0x1c) [0x55877c81567c]
> python3(+0x22bcb4) [0x55877c92bcb4]
> python3(PyRun_FileExFlags+0xa1) [0x55877c936191]
> python3(PyRun_SimpleFileExFlags+0x1c3) [0x55877c936383]
> python3(+0x237475) [0x55877c937475]
> python3(_Py_UnixMain+0x3c) [0x55877c93759c]
> /lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
> python3(+0x1dfb50) [0x55877c8dfb50]
> `
> Have you guys seen either of these issues?

I'm having the same issue here.

**Comment by yuanming-hu** [comment]
Thanks for reporting. Let me take a look today.

**Comment by yuanming-hu** [comment]
Should be fixed in v0.5.6. The buildbots are currently working on compiling/releasing the new version. Please let me know if that resolves your issue. Thanks so much for reporting this.

**Comment by tbarton16** [comment]
@yuanming-hu I have confirmed the examples run on my 19.01 machine. Thanks!
