### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by blessxu** [yuanming-hu/difftaichi#26]
I got a lot of DeprecationWarnings like 'ti.sqr(x) is deprecated, please use x ** 2 instead', then it doesn't work anymore. I think a warning won't let it crash. And I tried to fix these warnings, but still encounter some problems. 

Version
[Taichi] version 0.6.7, supported archs: [cpu, cuda, opengl], commit ca4d9dda, python 3.7.4
Ubuntu 
Linux version 5.3.0-53-generic (buildd@lgw01-amd64-016) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020

**Comment by yuanming-hu** [comment]
Sorry about that. That's clearly the desired behavior of warnings. I remove the usage of deprecated functions in most scripts, and will fix the warning behavior back in Taichi. For now, please just update difftaichi.
