### ISSUE TITLE
Taichi has no installable version `0.6.26`

### ISSUE THREAD

**Issue by rexwangcc** [yuanming-hu/difftaichi#42]
While the readme tells folks to use `taichi==0.6.26` to run `misc` examples, I got:

```
pip install taichi==0.6.26
ERROR: Could not find a version that satisfies the requirement taichi==0.6.26 (from versions: 0.5.15, 0.6.32, 0.6.33, 0.6.35, 0.6.36, 0.6.37, 0.6.39, 0.6.40, 0.6.41, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.8, 0.7.10, 0.7.14, 0.7.15, 0.7.16, 0.7.17, 0.7.18)
ERROR: No matching distribution found for taichi==0.6.26
```
which seems to indicate that Taichi has no installable version `0.6.26` anymore (on macOS)?

**Comment by yuanming-hu** [comment]
Thanks for reporting! We deleted the `0.6.26` release to save space on PyPI. Let me change that to `0.6.41 `.
