### ISSUE TITLE
Generating random numbers

### ISSUE THREAD

**Issue by aikkala** [yuanming-hu/difftaichi#5]
Is it possible to generate random numbers within the Tape? I've tried with `taichi.random(dt)` and using `numpy`; the first alternative crashes (see below for a minimal working example), and numpy generated random numbers don't seem to vary between iterations.

**MWE with taichi.random(dt)**
```
import taichi as ti

real = ti.f32
ti.set_default_fp(real)

scalar = lambda: ti.var(dt=real)
loss = scalar()
value = scalar()

@ti.layout
def place():
  ti.root.place(value)
  ti.root.place(loss)
  ti.root.lazy_grad()

@ti.kernel
def sample():
  value[None] = ti.random(dt=real)

def main():
  with ti.Tape(loss):
    sample()
    print(value[None])

main()
```

This example prints the generated random value and then crashes. 

Run-time generated log is [here](https://github.com/yuanming-hu/difftaichi/files/4059603/log.txt), and Taichi Compiler Stack Traceback is [here](https://github.com/yuanming-hu/difftaichi/files/4059602/stack_traceback.txt). Also I'm using Ubuntu 18.04 with PyCharm and anaconda.

**Comment by yuanming-hu** [comment]
Hi @aikkala 

Sorry about the delay. This is a good question. Random numbers are not supported in differentiable programming. My suggestion is to allocate a buffer of random numbers **outside** `ti.Tape` and read from it.
