### ISSUE TITLE
pip install not work?

### ISSUE THREAD

**Issue by arsuili** [yuanming-hu/difftaichi#7]
python3 -m pip install taichi-nightly  
ERROR: Could not find a version that satisfies the requirement taichi-nightly (from versions: none)
ERROR: No matching distribution found for taichi-nightly

**Comment by SJHNJU** [comment]
I also encountered the same problem. Is there any solutions or reason so far?
My python is 3.6.5

**Comment by SJHNJU** [comment]
I use conda to create a new python environment( python==3.7.6) and pip install work.
Maybe it is the python version problem
